select CUSTOMER_ACCOUNT_ID,
ACCOUNT_NUMBER,
EFFECTIVE_DATE,
MONTH_END_DT,
WEEK_END_DT,
ORGANIZATION_ID,
DIVISION_NAME,
REGION_NAME,
ACTIVITY,
ACTIVITYDETAIL,
ACTIVITYDETAIL_ORIGINAL,
X1_PLATFORM,
WEEKLY_SFLAG,
MONTHLY_SFLAG,
TOTAL_MRC_AMT,
TOTAL_MRM_AMT 
from EBI_NSD_VIEWS.NSD_X1_DAILY_ACTIVITY where to_char(EFFECTIVE_DATE,'YYYY-MM-DD')='2016-07-13' and customer_account_id IN ('514198772','514243542','513054424') ORDER BY CUSTOMER_ACCOUNT_ID;
Select ACTIVITYDETAIL, ACTIVITYDETAIL_ORIGINAL, AGNTFTAX,AUTOPAY_IND, B1, B1_TIER, BILLER_CREATED_BY, BILLER_SOURCE, BILLER_TECHNICIAN_ID, CDV, CDV_COST_AMT, CDV_MRC_AMT, CDV_MRM_AMT, CDV_TIER, CITY, CMCST_SUPER_SEG, COMPLEX_CD, CUSTOMER_ACCOUNT_ID, CUSTOMER_TYPE, DELQ_BAL_120_DAYS, DELQ_BAL_30_DAYS, DELQ_BAL_60_DAYS, DELQ_BAL_90_DAYS, DEMO_CHILDREN_NUM_HH, DEMO_COMP_FOOTPRINT, DEMO_DW_TYPE, DEMO_FIBER, DEMO_FIRST_INDV_AGE, DEMO_FIRST_INDV_EDU, DEMO_FIRST_INDV_GENDER, DEMO_HISPANIC_IND, DEMO_HOME_OWN_RENT, DEMO_INCOME_CODE, DEMO_LEN_OF_RES, DEMO_MARITAL_STATUS, DEMO_SECOND_INDV_AGE, DEMO_SECOND_INDV_GENDER, DISCO_REASON_ROLLUP_GROUP_NM, DISCO_REASON_ROLLUP_NM, DISCONNECT_REASON_CD, DISCONNECT_TYPE_CD, DISCONNECT_TYPE_NM, DIVISION_NAME, DMA_CODE, DMA_NAME, DUP_FLAG, DWELL_TYPE_GROUP_BILLER, ECOBILL_IND, EFFECTIVE_DATE, ENTITY_ID, ENTITY_NAME, ENTRY_OPER_SALES_CHANNEL_ID, ETHNICITY_CODE, FIBER_NODE_DESC, FIBER_NODE_NM, FINAL_DISCONNECT_TYPE, FINAL_SALES_CHANNEL_ID, FIPS_CODE, HISP_FOOTPRINT_SEG, HOUSE_NUMBER, HS, HS_TIER, HSD_COST_AMT, HSD_MRC_AMT, HSD_MRM_AMT, HSI, HSI_TIER, LATE_FEE_REVENUE_AMT, LATITUDE, LOCATION_ID, LONGITUDE, MONTH_END_DT, ORDER_IS_SIK_IND, ORDER_LINE_COMPLETION_DATE, ORDER_LINE_SALES_REP_ID, ORDER_NUM, ORDER_STATUS, ORGANIZATION_ID, PREV_CDV_MRC_AMT, PREV_CDV_MRM_AMT, PREV_HSD_MRC_AMT, PREV_HSD_MRM_AMT, PREV_TOTAL_MRC_AMT, PREV_TOTAL_MRM_AMT, PREV_VIDEO_MRC_AMT, PREV_VIDEO_MRM_AMT, PREV_XH_MRC_AMT, PREV_XH_MRM_AMT, PRIN, PRODUCT_MIX, REGION_NAME, SALES_REP_SALES_CHANNEL_CD_SO, SALES_REP_SALES_CHANNEL_ID, SAMOTO_CD, SCHEDULED_DATE, SERVICE_ORDER_CREATED_DATE, SERVICE_ORDER_ID, STATE, SYSCORP, T_DEST_CUSTOMER_ACCOUNT_ID, T_DEST_LOCATION_ID, T_SOUCRE_LOCATION_ID, T_SOURCE_CUSTOMER_ACCOUNT_ID, TOTAL_COST_AMT, TOTAL_MRC_AMT, TOTAL_MRM_AMT, TRANSFER_FLAG, VIDEO_COST_AMT, VIDEO_MRC_AMT, VIDEO_MRM_AMT, WEEK_END_DT, XH_COST_AMT, XH_MRC_AMT, XH_MRM_AMT, ZIP, ZIP4 from EBI_NSD_VIEWS.nsd_cancelled_wo where CUSTOMER_ACCOUNT_ID IN ('514198772','514243542','513054424') and to_char(EFFECTIVE_DATE , 'MM/DD/YYYY')='07/09/2016' ORDER BY ACTIVITYDETAIL_ORIGINAL;

